version: '3.8'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
#    networks:
#      - kafka-net

  kafka-broker-1:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka-broker-1
    depends_on:
      - zookeeper
    ports:
      - "8097:8097"
    expose:
      - "29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8097,INTERNAL://kafka-broker-1:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#    networks:
#      - kafka-net

  kafka-broker-2:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka-broker-2
    depends_on:
      - zookeeper
    ports:
      - "8098:8098"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8098,INTERNAL://kafka-broker-2:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#    networks:
#      - kafka-net

  init-kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      kafka-topics --bootstrap-server kafka-broker-1:29092 --list
      
      kafka-topics --bootstrap-server kafka-broker-1:29092 --create --if-not-exists --topic incoming-transactions --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka-broker-1:29092 --create --if-not-exists --topic categorized-transactions --replication-factor 1 --partitions 1
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-broker-1:29092 --list
      "

#networks:
#  kafka-net:
#    driver: bridge