spring:
  application.name: ingestion-service
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: ingestion-client
      group-id: ingestion-group

topic.name.transaction-ingestion: incoming-transactions

logging:
  level.root: INFO
  pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management.tracing.sampling.probability: 1.0